/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veritabaniproje;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erkan
 */
public class BuyingPage extends javax.swing.JFrame {

    /**
     * Creates new form BuyingPage
     */
    DefaultTableModel myModel;
    public BuyingPage() {
        initComponents();
        init();
    }
    
    public void init(){
        myModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            } 
        };
        String tc = VeriTabaniProje.customer.getTcno();
        String sqlquery = "select * from arsalar except select * from arsalar where arsalar.tapuno in (select tapuno from sahiplik where tcno='"+tc+"')";
        
       
        
        
        Object[] columns = {"Tapu No","İl","İlçe","Mahalle","Fiyat"};
        Object[] rows = new Object[5];
        
        myModel.setColumnCount(0);
        myModel.setRowCount(0);
        myModel.setColumnIdentifiers(columns);
        
        ResultSet rs = DBConnection.list(sqlquery);
        
        try {
            while(rs.next()){
                rows[0]=rs.getString("tapuno");
                rows[1]=rs.getString("il");
                rows[2]=rs.getString("ilçe");
                rows[3]=rs.getString("mahalle");
                rows[4]=rs.getString("fiyat");
                myModel.addRow(rows);
                        
                        
            }
             jTable1.setModel(myModel);
        } catch (SQLException e) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, e);

        }
        
        
        
    }
    
    
    public void refreshTable(){
         String tc = VeriTabaniProje.customer.getTcno();
        String sqlquery = "select* from arsalar where arsalar.tapuno in (select tapuno from sahiplik where tcno!='"+tc+"')";
        
       
        
        
        Object[] columns = {"Tapu No","İl","İlçe","Mahalle","Fiyat"};
        Object[] rows = new Object[5];
        
        myModel.setColumnCount(0);
        myModel.setRowCount(0);
        myModel.setColumnIdentifiers(columns);
        
        ResultSet rs = DBConnection.list(sqlquery);
        
        try {
            while(rs.next()){
                rows[0]=rs.getString("tapuno");
                rows[1]=rs.getString("il");
                rows[2]=rs.getString("ilçe");
                rows[3]=rs.getString("mahalle");
                rows[4]=rs.getString("fiyat");
                myModel.addRow(rows);
                        
                        
            }
             jTable1.setModel(myModel);
        } catch (SQLException e) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, e);

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSatinAl = new javax.swing.JButton();
        jButtonGeri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonSatinAl.setText("Satın Al");
        jButtonSatinAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSatinAlActionPerformed(evt);
            }
        });

        jButtonGeri.setText("Geri");
        jButtonGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(85, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGeri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonSatinAl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jButtonSatinAl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGeri)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeriActionPerformed
        // TODO add your handling code here
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        mainPage.pack();
        mainPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonGeriActionPerformed

    private void jButtonSatinAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSatinAlActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        Object tapuNo = model.getValueAt(selectedRow, 0);
        tapuNo = (String) tapuNo;
        Object fiyat = model.getValueAt(selectedRow, 4);
        Integer ekstra = Integer.parseInt(fiyat.toString());
        ekstra = ekstra *5 /100;
        Integer toplam = Integer.parseInt(fiyat.toString())+ekstra+1500;
        String tc = VeriTabaniProje.customer.getTcno();
        String sqlquery = "select tcno from sahiplik where tapuno= '"+tapuNo+"'";
        String TC = "";
        String query = "update sahiplik set tcno = '"+tc+"' where tapuno = '"+tapuNo+"'";
        try {
            
            PreparedStatement preparedStatement1 = DBConnection.connection.prepareStatement(sqlquery);
            ResultSet rs = preparedStatement1.executeQuery();
            if(rs.next()){
                TC = rs.getString(1);  
            }
            DBConnection.insertIslem(tapuNo.toString(), tc, TC, fiyat.toString(), ekstra.toString(), toplam.toString());
             PreparedStatement preparedStatement = DBConnection.connection.prepareStatement(query);
            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Arsa Satın Alındı");
        } catch (SQLException e) {
            Logger.getLogger(BuyingPage.class.getName()).log(Level.SEVERE,null,e);
        }
        
        refreshTable();
        
        
    }//GEN-LAST:event_jButtonSatinAlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGeri;
    private javax.swing.JButton jButtonSatinAl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
